#pragma once
#include "MessageIdentifiers.h"

enum RRPG_ID : unsigned char
{
	S_PLAYER_CONNECTED = ID_USER_PACKET_ENUM,
	S_GAME_STARTED,
	S_REPLY_PLAYER_LIST_REQUEST,
	C_INTRO,
	C_READY,
	C_UNREADY,
	C_PLAYER_LIST_REQUEST
};